### ISSUE TITLE
problem: "edge with zero length"

### ISSUE THREAD

**Issue by venico19** [ohinai/mesher#1]
input file: 

build_mesh 0 1 0 1 20 20
add_vertex         0.0000000        0.7000000
add_vertex         0.9348654        0.9992852
 add_edge -1 -2
 set_fracture -1
add_vertex         0.1000000        0.3000000
add_vertex         0.4900921        0.6442873
 add_edge -1 -2
 set_fracture -1
add_vertex         0.3000000        0.4000000
add_vertex         0.0000000        0.8980085
 add_edge -1 -2
 set_fracture -1
add_vertex         0.5000000        0.5000000
add_vertex         0.2498297        0.0000000
 add_edge -1 -2
 set_fracture -1
add_vertex         1.0000000        0.2000000
add_vertex         0.7265414        0.8298096
 add_edge -1 -2
 set_fracture -1
 intersect_fractures
 remove_leaves
 merge_fracture_vertices .0001
 polygons
 mimpy_mesh mesh1.mesh

**Comment by ohinai** [comment]
Have you tried pulling the latest version from the repo? I tried your example file, and it seems to be working. Let me know if you have trouble!

**Comment by venico19** [comment]
It works!
